"""Verify the TS 26.926 XR traffic model generated by a2_xr_traffic.cc.

Reads xr_frames.csv / xr_rx_packets.csv and plots PDF + CDF of
  - frame size        vs. theoretical truncated Gaussian
  - frame jitter      vs. theoretical truncated Gaussian
  - frame inter-arrival vs. theoretical (1/fps + difference of two jitters)
  - IP packet size and packet inter-arrival seen at the receiver
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]

# Model parameters (fps, bit rate, eye buffers, jitter) are read from
# xr_model.csv written by a2_xr_traffic.cc. Frame size follows TS 26.926
# Table 6.5.3.1-1: mean M = R * 1e6 / (E * F) / 8, STD 10.5% of M, range [50%, 150%].
IP_UDP_HEADER = 28


def read_csv(path: Path) -> dict[str, np.ndarray]:
    with path.open(newline="") as f:
        rows = list(csv.DictReader(f))
    return {k: np.array([float(r[k]) for r in rows]) for k in rows[0]}


def trunc_norm_pdf(x, mean, std, bound):
    phi = lambda z: math.erf(z / math.sqrt(2))
    mass = phi(bound / std)  # P(|X - mean| <= bound)
    pdf = np.exp(-0.5 * ((x - mean) / std) ** 2) / (std * math.sqrt(2 * math.pi)) / mass
    return np.where(np.abs(x - mean) <= bound, pdf, 0.0)


def theory_cdf(x, pdf):
    cdf = np.concatenate([[0.0], np.cumsum((pdf[1:] + pdf[:-1]) / 2 * np.diff(x))])
    return cdf / cdf[-1]


def ks_statistic(samples, x, cdf):
    s = np.sort(samples)
    model = np.interp(s, x, cdf)
    n = len(s)
    return max(np.max(np.arange(1, n + 1) / n - model), np.max(model - np.arange(n) / n))


def plot_model(samples, x, pdf, xlabel, title, stem, out: Path, bins=50) -> float:
    cdf = theory_cdf(x, pdf)
    d = ks_statistic(samples, x, cdf)
    fig, axes = plt.subplots(1, 2, figsize=(11, 4), constrained_layout=True)
    axes[0].hist(samples, bins=bins, density=True, color="#93c5fd", edgecolor="white",
                 label=f"ns-3 output (n={len(samples)})")
    axes[0].plot(x, pdf, color="#dc2626", lw=2, label="TS 26.926 theory")
    axes[0].set(title=f"{title} PDF", xlabel=xlabel, ylabel="Density")
    axes[0].legend()
    s = np.sort(samples)
    axes[1].step(s, np.arange(1, len(s) + 1) / len(s), where="post", color="#2563eb", lw=2,
                 label="ns-3 output (empirical)")
    axes[1].plot(x, cdf, "--", color="#dc2626", lw=2, label="TS 26.926 theory")
    axes[1].set(title=f"{title} CDF  (KS D = {d:.4f})", xlabel=xlabel, ylabel="CDF")
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()
    fig.savefig(out / f"{stem}.png", dpi=180)
    plt.close(fig)
    return d


def plot_empirical(samples, xlabel, title, stem, out: Path, log_x=False) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(11, 4), constrained_layout=True)
    bins = np.logspace(np.log10(samples.min()), np.log10(samples.max()), 60) if log_x else 60
    # Log y-axis so the small tail (last fragment of each frame / inter-frame gap)
    # stays visible next to the dominant full-size, back-to-back packets.
    axes[0].hist(samples, bins=bins, color="#93c5fd", edgecolor="white")
    axes[0].set(title=f"{title} histogram", xlabel=xlabel, ylabel="Count (log scale)", yscale="log")
    s = np.sort(samples)
    axes[1].step(s, np.arange(1, len(s) + 1) / len(s), where="post", color="#2563eb", lw=2)
    axes[1].set(title=f"{title} CDF", xlabel=xlabel, ylabel="CDF")
    axes[1].grid(True, alpha=0.3)
    for ax in axes:
        if log_x:
            ax.set_xscale("log")
    fig.savefig(out / f"{stem}.png", dpi=180)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", type=Path, default=ROOT / "results")
    out = parser.parse_args().results

    frames = read_csv(out / "xr_frames.csv")
    rx = read_csv(out / "xr_rx_packets.csv")

    with (out / "xr_model.csv").open(newline="") as f:
        model = {r["parameter"]: float(r["value"]) for r in csv.DictReader(f)}
    FPS = model["fps"]
    STD_JITTER, BOUND_JITTER = model["jitter_std_ms"], model["jitter_bound_ms"]
    num_eyes = int(model["eye_buffers"])
    eyes = frames["eye"].astype(int)
    MEAN_FRAME = model["bit_rate_mbps"] * 1e6 / (num_eyes * FPS) / 8
    STD_FRAME, BOUND_FRAME = 0.105 * MEAN_FRAME, 0.5 * MEAN_FRAME

    # Frame size
    x = np.linspace(MEAN_FRAME - 1.1 * BOUND_FRAME, MEAN_FRAME + 1.1 * BOUND_FRAME, 4001)
    d_size = plot_model(frames["size_bytes"], x, trunc_norm_pdf(x, MEAN_FRAME, STD_FRAME, BOUND_FRAME),
                        "Frame size (bytes)", "XR frame size", "frame_size_pdf_cdf", out)

    # Jitter
    xj = np.linspace(-BOUND_JITTER - 1, BOUND_JITTER + 1, 4001)
    jitter_pdf = trunc_norm_pdf(xj, 0.0, STD_JITTER, BOUND_JITTER)
    d_jit = plot_model(frames["jitter_ms"], xj, jitter_pdf, "Jitter (ms)", "XR frame jitter",
                       "frame_jitter_pdf_cdf", out)

    # Frame inter-arrival = period + J_{k+1} - J_k  ->  pdf is the jitter pdf convolved with itself
    # (computed within each eye buffer stream, then pooled)
    ia_ms = np.concatenate([np.diff(np.sort(frames["gen_time_s"][eyes == e])) * 1000.0
                            for e in np.unique(eyes)])
    dx = xj[1] - xj[0]
    diff_pdf = np.convolve(jitter_pdf, jitter_pdf[::-1]) * dx
    xd = np.arange(len(diff_pdf)) * dx - (len(xj) - 1) * dx + 1000.0 / FPS
    d_ia = plot_model(ia_ms, xd, diff_pdf, "Frame inter-arrival time (ms)", "XR frame inter-arrival",
                      "frame_interarrival_pdf_cdf", out)

    # Network-level view at the receiver
    ip_size = rx["udp_payload_bytes"] + IP_UDP_HEADER
    plot_empirical(ip_size, "IP packet size (bytes)", "Received IP packet size",
                   "packet_size_pdf_cdf", out)
    pkt_ia_ms = np.diff(np.sort(rx["rx_time_s"])) * 1000.0
    plot_empirical(pkt_ia_ms, "Packet inter-arrival time (ms, log scale)",
                   "Received packet inter-arrival", "packet_interarrival_pdf_cdf", out, log_x=True)

    # Frame delay = last packet of the frame received - frame generation time
    last_rx = {}
    for fid, t in zip(rx["frame_id"].astype(int), rx["rx_time_s"]):
        last_rx[fid] = max(t, last_rx.get(fid, 0.0))
    frame_delay = np.array([(last_rx[int(f)] - g) * 1000.0
                            for f, g in zip(frames["frame_id"], frames["gen_time_s"])
                            if int(f) in last_rx])

    lines = [
        "A2 TS 26.926 XR traffic distribution summary",
        f"Eye buffers: {num_eyes}, frames: {len(frames['size_bytes'])}, received packets: {len(ip_size)}",
        f"Frame size mean/std bytes: {frames['size_bytes'].mean():.1f} / {frames['size_bytes'].std():.1f}"
        f"  (theory {MEAN_FRAME:.1f} / ~{STD_FRAME:.1f}), KS D = {d_size:.4f}",
        f"Jitter mean/std ms: {frames['jitter_ms'].mean():.3f} / {frames['jitter_ms'].std():.3f}"
        f"  (theory 0 / ~{STD_JITTER:.1f}, truncated at +/-{BOUND_JITTER:g}), KS D = {d_jit:.4f}",
        f"Frame inter-arrival mean ms: {ia_ms.mean():.3f}  (theory {1000 / FPS:.3f}), KS D = {d_ia:.4f}",
        f"KS 5% critical value ~ {1.36 / math.sqrt(len(frames['size_bytes'])):.4f}",
        f"Packet inter-arrival median ms: {np.median(pkt_ia_ms):.4f}",
        f"Frame delay mean / p95 / max ms: {frame_delay.mean():.3f} / "
        f"{np.percentile(frame_delay, 95):.3f} / {frame_delay.max():.3f}",
        f"Packet delay mean / max ms: {rx['delay_ms'].mean():.3f} / {rx['delay_ms'].max():.3f}",
    ]
    (out / "xr_distribution_summary.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
